name: app
version: 0.0.1
publish_to: "none"
description: Open source budgeting.
environment: { sdk: ">=3.4.3 <4.0.0" }

dependencies:
  bloc: ^8.1.4
  flex_color_scheme: ^7.3.1
  flutter: { sdk: flutter }
  flutter_adaptive_scaffold: ^0.1.11
  flutter_bloc: ^8.1.6
  flutter_gutter: ^1.0.2
  go_router: ^14.2.0
  pocketbase: ^0.18.1
  shared_preferences: ^2.2.3

dev_dependencies:
  archive: ^3.6.1
  flutter_test: { sdk: flutter }
  http: ^1.2.1
  mason_logger: ^0.2.15
  path: ^1.9.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
